[tox]
envlist = py310,py311,py312,lint
isolated_build = true

[testenv]
deps = -rrequirements-dev.txt
commands =
    python -m pytest

[testenv:lint]
deps = -rrequirements-dev.txt
commands =
    ruff check s1downloader tests
    ruff format --check s1downloader tests
